
[libraries]
lib.files = [
  "test.vhdl"
]
vunit_lib.files = [
  "third_party/vunit/src/vunit/vhdl/string_ops/src/string_ops.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/types.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/api/external_integer_vector_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/codec_builder.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/codec_builder-2008p.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/codec.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/codec-2008p.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/integer_vector_ptr_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/integer_vector_ptr_pool_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/api/external_string_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/string_ptr_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/core/src/stop_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/core/src/stop_body_2008p.vhd",
  "third_party/vunit/src/vunit/vhdl/core/src/core_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/id_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/logging/src/ansi_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/logging/src/log_levels_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/logging/src/common_log_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/logging/src/file_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/logging/src/log_handler_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/logging/src/print_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/logging/src/location_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/string_ptr_pool_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/byte_vector_ptr_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/data_types_private_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/integer_array_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/queue_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/dict_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/dict_pkg-2008p.vhd",
  "third_party/vunit/src/vunit/vhdl/logging/src/logger_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/integer_array_pkg-body.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/dict_pkg-body.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/event_common_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/event_private_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/event_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/queue_pkg-body.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/queue_pkg-2008p.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/queue_pool_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/logging/src/common_log_pkg-body.vhd",
  "third_party/vunit/src/vunit/vhdl/logging/src/location_pkg-body-2019p.vhd",
  "third_party/vunit/src/vunit/vhdl/logging/src/log_handler_pkg-body.vhd",
  "third_party/vunit/src/vunit/vhdl/logging/src/log_levels_pkg-body.vhd",
  "third_party/vunit/src/vunit/vhdl/logging/src/logger_pkg-body.vhd",
  "third_party/vunit/src/vunit/vhdl/logging/src/print_pkg-body.vhd",
  "third_party/vunit/src/vunit/vhdl/check/src/checker_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/check/src/check_api.vhd",
  "third_party/vunit/src/vunit/vhdl/check/src/check_api-2008p.vhd",
  "third_party/vunit/src/vunit/vhdl/check/src/check.vhd",
  "third_party/vunit/src/vunit/vhdl/check/src/check-2008p.vhd",
  "third_party/vunit/src/vunit/vhdl/check/src/checker_pkg-body.vhd",
  "third_party/vunit/src/vunit/vhdl/dictionary/src/dictionary.vhd",
  "third_party/vunit/src/vunit/vhdl/random/src/random_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/path/src/path.vhd",
  "third_party/vunit/src/vunit/vhdl/data_types/src/data_types_context.vhd",
  "third_party/vunit/src/vunit/vhdl/run/src/run_types.vhd",
  "third_party/vunit/src/vunit/vhdl/run/src/runner_pkg.vhd",
  "third_party/vunit/src/vunit/vhdl/run/src/run_api.vhd",
  "third_party/vunit/src/vunit/vhdl/run/src/run.vhd",
  "third_party/vunit/src/vunit/vhdl/vunit_context.vhd",
  "third_party/vunit/src/vunit/vhdl/vunit_run_context.vhd"
]
